# NumPy 和陣列導向的程式設計

`NumPy` 可以說是 Python 中最最標準的科學計算、數據分析套件。也因為 `NumPy` 的出現, 讓 Python 有了非常好的數據分析基礎, 一直到現在成為數據分析覇主。

In [62]:
import numpy as np

## 1. 陣列導向 101

科學計算一個很核心的概念叫 "array oriented" 的寫法。Array 是 `numpy` 標準的資料結構, 和 list 很像, 但就差了那麼一點點。而這一點點讓我們在計算上是無比的方便。

In [63]:
grades = [77, 85, 56, 90, 66]
arr = np.array(grades)
arr.mean()

74.8

### 【暖身】 計算平均

某位同學期中考各科成績如下, 請幫他計算成績。

    grades = [77, 85, 56, 90, 66]
    
請計算平均。

In [61]:
grades = [77, 85, 56, 90, 66]
s = 0
for i in grades:
    s = s + i

print("Average: {0:.2f} ".format(s/len(grades)))    #{}字串裡的中括弧會搜尋 .format後括弧裡的值，
                                                    #0代表format後第幾格變數，冒號後面是格式化輸出
                                                    #2f代表資料型態，float小數點後兩位

Average: 74.80 


### 【示範】陣列導向

最大值

In [66]:
print("Maximum:", arr.max())

Maximum: 90


標準差

In [67]:
print("Standard Deviation", arr.std())

Standard Deviation 12.416118556135006


### 【暖身】 換算匯率

假設今天我想查查號稱 Pentax 三公主的 31mm, 43mm, 77mm 三隻 limited 鏡頭在美國賣多少。於是我去 B&H 查了他們的價格分別是:

    prices = [1096.95, 596.95, 896.95]
    
我又查了 Google 匯率 1 美金為 31.71 元。請把三支鏡頭的價格換算為台幣。

In [76]:
prices = [1096.95, 596.95, 896.95]
usd2twd = 31.71
twd_prices = []

for i in range(len(prices)):
    prices[i] *= usd2twd
    twd_prices.append(prices[i])

print("Prices in TWD:", twd_prices)

Prices in TWD: [34784.2845, 18929.2845, 28442.2845]


先不管這實在有夠醜的數字, 我們要記得在科學計算中:

### 儘可能不要使用迴圈

這可能嗎?

### 【示範】陣列換算匯率

In [78]:
prices = np.array([1096.95, 596.95, 896.95])
twd = 31.71 * prices
print("Prices in TWD:", twd)

Prices in TWD: [34784.2845 18929.2845 28442.2845]


哦哦, 傑克, 這太神奇了!

## 2. 其實 array 還有很多功能

### 【練習】 成績計算

一位老師成績這樣算的:

* 平時成績 20%
* 期中考   35%
* 期未考   45%

有位同學

* 平時成績 85 分
* 期中 70 分
* 期末 80 分

這位同學的學期成績是多少?

In [81]:
grades = np.array([85,70,80])
weights = np.array([0.2, 0.35, 0.45])

這還不是我們要的最終成績啊!

In [23]:
grades = np.array([85,70,80])
weights = np.array([0.2, 0.35, 0.45])
weighted_grades = grades * weights
Sum = 0

for i in range(0, len(grades)):
    Sum += weighted_grades[i]

print(Sum)

77.5


### 【提示】 array 還有很多函數可以用

可以先打入

    weighted_grades.
    
先不要按 `enter` 或 `shift-enter`, 而是按 `tab`...


In [20]:
weighted_grades.sum()

77.5

### 【技巧】 一行完成成績計算

In [82]:
np.dot(grades, weights)

77.5

## 3. 重要的 array 大變身!

我們在數據分析, 常常要改 array 的型式。

### 【練習】 一個 50 個數字的 array

先想辦法、用亂數做出 50 個數字的 array, 叫做 A 好了。

In [83]:
A = random.rand(50)    #rand產生0到1之間的數值
A

array([0.70046856, 0.76313042, 0.22970419, 0.66300797, 0.85775406,
       0.80644853, 0.51586075, 0.1224715 , 0.35916621, 0.13131376,
       0.12063512, 0.35797355, 0.0653877 , 0.23416335, 0.71637772,
       0.73311553, 0.68376104, 0.44754211, 0.14464431, 0.77904846,
       0.08239978, 0.80847523, 0.05271332, 0.62732105, 0.01003058,
       0.40019668, 0.80110869, 0.39917519, 0.63903782, 0.53435358,
       0.13211439, 0.80129032, 0.65515288, 0.9221802 , 0.0416605 ,
       0.27761631, 0.85102405, 0.45472033, 0.82209313, 0.72749814,
       0.30239407, 0.92395906, 0.40831537, 0.43129991, 0.7745861 ,
       0.03831161, 0.0900662 , 0.46826599, 0.86786674, 0.08690212])

### 【技巧】 檢查 A 的 `shape`

In [85]:
A.shape

(50,)

### 【技巧】 更改 A 的 shape

In [86]:
A.shape = (5, 10)
A

array([[0.70046856, 0.76313042, 0.22970419, 0.66300797, 0.85775406,
        0.80644853, 0.51586075, 0.1224715 , 0.35916621, 0.13131376],
       [0.12063512, 0.35797355, 0.0653877 , 0.23416335, 0.71637772,
        0.73311553, 0.68376104, 0.44754211, 0.14464431, 0.77904846],
       [0.08239978, 0.80847523, 0.05271332, 0.62732105, 0.01003058,
        0.40019668, 0.80110869, 0.39917519, 0.63903782, 0.53435358],
       [0.13211439, 0.80129032, 0.65515288, 0.9221802 , 0.0416605 ,
        0.27761631, 0.85102405, 0.45472033, 0.82209313, 0.72749814],
       [0.30239407, 0.92395906, 0.40831537, 0.43129991, 0.7745861 ,
        0.03831161, 0.0900662 , 0.46826599, 0.86786674, 0.08690212]])

### 【技巧】 也可以用 `reshape`

但要注意, reshape 並沒有改原來的陣列。

In [88]:
A.reshape(10, 5)
A

array([[0.70046856, 0.76313042, 0.22970419, 0.66300797, 0.85775406,
        0.80644853, 0.51586075, 0.1224715 , 0.35916621, 0.13131376],
       [0.12063512, 0.35797355, 0.0653877 , 0.23416335, 0.71637772,
        0.73311553, 0.68376104, 0.44754211, 0.14464431, 0.77904846],
       [0.08239978, 0.80847523, 0.05271332, 0.62732105, 0.01003058,
        0.40019668, 0.80110869, 0.39917519, 0.63903782, 0.53435358],
       [0.13211439, 0.80129032, 0.65515288, 0.9221802 , 0.0416605 ,
        0.27761631, 0.85102405, 0.45472033, 0.82209313, 0.72749814],
       [0.30239407, 0.92395906, 0.40831537, 0.43129991, 0.7745861 ,
        0.03831161, 0.0900662 , 0.46826599, 0.86786674, 0.08690212]])

### 【技巧】 拉平 `ravel`

雖然你想一想就知道可以用 `shape` 或 `reshape` 把多維陣列拉成一維。不過用 `ravel` 很潮。

In [89]:
A.ravel()

array([0.70046856, 0.76313042, 0.22970419, 0.66300797, 0.85775406,
       0.80644853, 0.51586075, 0.1224715 , 0.35916621, 0.13131376,
       0.12063512, 0.35797355, 0.0653877 , 0.23416335, 0.71637772,
       0.73311553, 0.68376104, 0.44754211, 0.14464431, 0.77904846,
       0.08239978, 0.80847523, 0.05271332, 0.62732105, 0.01003058,
       0.40019668, 0.80110869, 0.39917519, 0.63903782, 0.53435358,
       0.13211439, 0.80129032, 0.65515288, 0.9221802 , 0.0416605 ,
       0.27761631, 0.85102405, 0.45472033, 0.82209313, 0.72749814,
       0.30239407, 0.92395906, 0.40831537, 0.43129991, 0.7745861 ,
       0.03831161, 0.0900662 , 0.46826599, 0.86786674, 0.08690212])

## 4. 快速 array 生成法

### 【技巧】 都是 0 的 array

In [90]:
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### 【技巧】 都是 1 的 array

In [39]:
np.ones(10)   #生成圖像，0為黑色，1為白色


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### 【技巧】單位矩陣

In [92]:
zeroes = np.zeros((5, 5))

for i in range(5):
    zeroes[i, i] = 1

zeroes

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [91]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 【技巧】給定範圍均勻生出 n 個點

In [93]:
x = np.linspace(0, 10, 100)  #linspace function 根據括弧內的範圍（0到10）切出100個位子
x

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

### 【技巧】`range` 的 array 版

就是 `arange`。

In [95]:
#arange = range in array
np.arange(1, 10, 0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

## 5. 超重要 `axis` 觀念

初學 `numpy` 很多人有點弄不清楚 `axis` 概念。其實掌握矩陣, 或很像矩陣的陣列都是「先列後行」就可以!

我們先弄個 array 來練習。

In [105]:
a = np.arange(0,10).reshape((2, 5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 【重點】 一列一列算下來是 `axis=0`

![axis=0](images/axis0.png)

In [103]:
a.sum(axis = 0)

array([ 5,  7,  9, 11, 13])

### 【重點】 一行一行算過去是 `axis=1`

![axis=1](images/axis1.png)

In [106]:
a.sum(axis = 1)

array([10, 35])

### 【提示】當然也有可能全部算

In [107]:
a.sum()

45

## 6. array 過濾器

篩出我們要的資料, 這樣的技巧非常重要!

### 【例子】篩出大於 0 的數

我們有個陣列, 想找出大於 0 的數。<br>
L = np.array([3, -2, -1, 5, 7, -3])

In [109]:
L = np.array([3, -2, -1, 5, 7, -3])

我們可以很白痴的自己判斷...<br>
c = np.array([True,False,False,True,True,False])

In [110]:
c = np.array([True,False,False,True,True,False])

這是做啥呢? 我們可以瞬間...

In [112]:
L[c]  #括弧內篩選條件

array([3, 5, 7])

除了自己做很白痴, 這看來很厲害!

事實上我們可以叫 `numpy` 做!

In [113]:
L > 0

array([ True, False, False,  True,  True, False])

這有點強, 我們還可以一次到位!

In [114]:
L[L>0]

array([3, 5, 7])

In [115]:
L    #並不改變原始的陣列，因為沒有assign回去給原本的陣列

array([ 3, -2, -1,  5,  7, -3])

## 7. 次元切割刀

`numpy` 中 array 的切割法和 list 很像。

In [117]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
x[3:7]

array([3, 4, 5, 6])

### 【技巧】2維陣列切法

記得先列後行!

In [121]:
y = np.arange(10).reshape(2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

要所有的row, 切出行 1-3 位置。

In [125]:
y[:,1:3]    #所有的row用一個冒號表示即可

array([[1, 2],
       [6, 7]])

要所有的行col, 切出第 1 列row!

In [126]:
y[1,:] 

array([5, 6, 7, 8, 9])

## 8. `NumPy` 的 `zip` 和 `unzip`

之前我們介紹 list 可以用 `zip` 和 `unzip` (其實還是 `zip`) 做到的資料格式變換, 在 array 中怎麼做呢?

![zip and unzip](images/zip.png)

### 【重點】array 的 `zip`

![array zip](images/arrzip.png)

In [131]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

In [135]:
X = np.c_[x,y]    #c stands for column, followed by the values of each column, here we have x and y
X                 #kinda like transpose here

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [138]:
Y = np.r_[x,y]
Y

array([1, 2, 3, 4, 5, 6, 7, 8])

### 【重點】array 的 `unzip`

這裡其實只需要用到 array 的切割法...

![array zip](images/arrunzip.png)

In [139]:
X[:,0]    #unzip, for all the rows in X, unzipping column 0, which we'd get values 1, 2, 3 4

array([1, 2, 3, 4])